#5/ id를 통한 유저조회 + 프로필 수정 -> 비밀번호 변경 API + Method 분리
llocr/StudyWithMe pull request #23
Opened 2024-06-07 14:12 UTC by backendINFJ

## 📌 연관된 이슈

> Issue Number : #이슈번호

## PR 종류
해당 PR은 어떤 부분에 대한 변화인가요?

- [ ] 버그 수정 `FIX`(Hotfix)
- [x] 코드 수정 `MODIFY`
- [x] 기능 추가 `FEAT`
- [x] 파일 이름 변경 `RENAME`
- [ ] 테스트 코드 추가 `TEST`
- [ ] 코드 스타일 변화 (formatting, local variables) `STYLE`
- [x] 리팩토링 (no functional changes, no api changes) `REFACTOR`
- [ ] 빌드 관련 내용 추가 및 변화 `BUILD`
- [ ] 문서 내용 추가 및 변화`DOCS`
- [ ] 기타 변경 사항 추 `CHORE`
- [ ] Other... (적어주세요 : )

## 💻 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해 주세요 (이미지 첨부 가능)

- pk값인 Long id를 통해 유저를 조회하는 기능을 구현했습니다.
- 프로필 수정시 변경된 필드는 변경된 값으로 업데이트가 되고 수정을 하지 않은 데이터는 기존 데이터를 유지하게 구현했습니다.
- 프로필 수정시 비밀번호의 포지션이 애매했습니다. 가령 유저가 현재 비밀번호를 입력하지 않으면 프로필이 수정이 되지 않게 구현을 했기에
비밀번호가 null값일 수 없습니다 따라서 매번 비밀번호를 변경하는 이슈가 발생했었고 이에따라 비밀번호 변경 API를 따로 만들어 비밀번호 로직을 따로 분리하였습니다.

## 해당 PR이 다른 영역에 영향을 미치나요?
- [ ] Yes
- [x] No

## 💬 리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-06-07 14:55 UTC, llocr requested changes
코드 짜느라 수고하셨어요!
몇 개 부분만 수정해주시면 너어어무 좋을 것 같습니다 :) 👍

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
이 DTO를 이미 사용하고 있는 곳이 있는 것으로 알고 있습니다.
이미 사용하고 있는 DTO를 고치면 다른 메소드에서 문제가 생길 것 같습니다... :(

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
> +@Data
`@Data` 어노테이션을 사용하는 것보다, 낱개의 어노테이션을 선언해서 쓰는 것이 좋을 것 같네용!

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/UserProfileUpateRequestDTO.java
> +    private String currentPasdsword;
오타 있습니다 🫨

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/UserResponseDTO.java
> +		this.introduce = user.getIntroduce();
다른 곳에서 사용하는 DTO에서 문제가 생기진 않나요?
앞으로는 확인해보시고 수정하시는 게 좋을 것 같아요 :)

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
>      private String name;
이 필드들은 필요 없는 것이니 삭제해주셔도 될 것 같습니다

2024-06-07 14:55 UTC, llocr commented on src/main/java/december/spring/studywithme/service/UserService.java
> +        String editIntroduce = requestDTO.getIntroduce() != null ? requestDTO.getIntroduce() : user.getIntroduce();
null인지 아닌지 확인하는 거 좋네요!! 👍

2024-06-08 03:17 UTC, tichall commented on src/main/java/december/spring/studywithme/dto/UserProfileUpateRequestDTO.java
DTO명 오타 있습니다! Refactor 사용해 Upate -> Update로 파일명 변경해주시면 좋을 것 같아요!

2024-06-08 03:17 UTC, tichall commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
+) 이 DTO는 윤재님이 작성하신 코드에서는 사용하는 곳이 없어서 develop에 있는 기존 코드로 재수정해주시면 좋을 것 같습니다!

2024-06-08 05:37 UTC, backendINFJ commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
> +@Data
수정 완료했습니다~:)

2024-06-08 05:40 UTC, backendINFJ commented on src/main/java/december/spring/studywithme/dto/UserProfileUpateRequestDTO.java
> +    private String currentPasdsword;
ㅋㅋㅋㅋ아 너무 부끄럽네요 수정했습니다~~

2024-06-08 05:40 UTC, backendINFJ commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
>      private String name;
수정 완료했습니다~:)

2024-06-08 05:41 UTC, backendINFJ commented on src/main/java/december/spring/studywithme/service/UserService.java
> +        String editIntroduce = requestDTO.getIntroduce() != null ? requestDTO.getIntroduce() : user.getIntroduce();
코딩 테스트로 단련된 삼항연산자.. 드디어 빛을 보네요!!👍

2024-06-08 05:42 UTC, backendINFJ commented on src/main/java/december/spring/studywithme/dto/UserProfileUpateRequestDTO.java
ㅋㅋㅋ아 쥐구멍 어디에 있지..😅 수정했습니다~~

2024-06-09 11:39 UTC, llocr approved these changes
코드 작성하느라 수고하셨어요~~~ 👍

2024-06-09 11:39 UTC, llocr commented on src/main/java/december/spring/studywithme/dto/PasswordRequestDTO.java
> +@Setter
@Data 대신 @Getter, @Setter 사용 너무 좋습니다!

2024-06-09 11:39 UTC, merged